TeamDev-IP/JxBrowser-QuickStart

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
* Change version in `build.gradle` and `pom.xml` files.
> Bump JxBrowser version to 7.26

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
In this changeset, we change the JxBrowser version to 7.27
> Bump JxBrowser version to 7.27

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
* Change version in `Gradle/JavaFX-11/build.gradle`;
* Change version in `Gradle/Core/build.gradle`;
* Change version in `Gradle/JavaFX/build.gradle`;
* Change version in `Gradle/Swing/build.gradle`;
* Change version in `Gradle/SWT/build.gradle`;
* Change version in `Maven/Core/pom.xml`;
* Change version in `Maven/JavaFX/pom.xml`;
* Change version in `Maven/Swing/pom.xml`;
* Change version in `Maven/SWT/pom.xml`;
> Bump JxBrowser version to 7.28

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.28.1
> Bump JxBrowser to 7.28.1

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.29
> Bump JxBrowser to 7.29

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.30
> Bump JxBrowser to 7.30

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.30.1
> Bump JxBrowser to 7.30.1

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.30.2
> Bump JxBrowser to 7.30.2

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.30.3
> Bump JxBrowser to 7.30.3

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.31
> Bump JxBrowser to 7.31

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.31.1
> Bump JxBrowser to 7.31.1

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.32
> Bump JxBrowser to 7.32

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.33
> Bump JxBrowser to 7.33

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.33.1
> Bump JxBrowser to 7.33.1

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.33.2
> Bump JxBrowser to 7.33.2

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.34
> Update JxBrowser to v7.34

- Gradle/Core/build.gradle
- Gradle/JavaFX-11/build.gradle
- Gradle/JavaFX/build.gradle
- Gradle/SWT/build.gradle
- Gradle/Swing/build.gradle
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.34.1
> Update JxBrowser to v7.34.1

- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.35
In this changeset, we update: 
> Update JxBrowser to v7.35

- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.35.1
* Update Maven/Core/pom.xml
> Update JxBrowser to v7.35.1

- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.35.2
* Update Maven/Core/pom.xml
> Update JxBrowser to v7.35.2

- Gradle/Core/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.36
* Update Maven/Core/pom.xml
> Update JxBrowser to v7.36

- Gradle/Core/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
> Switch to the latest version of JxBrowser Gradle plugin

- Gradle/Core/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Core/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.36.1
* Update Maven/Core/pom.xml
> Update JxBrowser to v7.36.1

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.36.2
> Update JxBrowser to v7.36.2

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.37.0
* Update Gradle/Console/build.gradle.kts
* Update Gradle/JavaFX-11/build.gradle.kts
* Update Gradle/JavaFX/build.gradle.kts
* Update Gradle/SWT/build.gradle.kts
* Update Gradle/SWT/buildSrc/build.gradle.kts
* Update Gradle/Swing/build.gradle.kts
> Update JxBrowser to v7.37.0

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.37.1
* Update Gradle/Console/build.gradle.kts
* Update Gradle/JavaFX-11/build.gradle.kts
* Update Gradle/JavaFX/build.gradle.kts
* Update Gradle/SWT/build.gradle.kts
* Update Gradle/SWT/buildSrc/build.gradle.kts
* Update Gradle/Swing/build.gradle.kts
> Update JxBrowser to v7.37.1

- Gradle/Console/src/main/java/HelloConsole.java
- Gradle/JavaFX-11/README.md
- Gradle/JavaFX-11/src/main/java/HelloFX11.java
- Gradle/JavaFX/README.md
- Gradle/JavaFX/src/main/java/HelloFX.java
- Gradle/SWT/README.md
- Gradle/SWT/src/main/java/HelloSWT.java
- Gradle/Swing/README.md
- Gradle/Swing/src/main/java/HelloSwing.java
- Maven/Console/src/main/java/HelloConsole.java
- Maven/JavaFX/src/main/java/HelloFX.java
- Maven/SWT/src/main/java/HelloSWT.java
- Maven/Swing/src/main/java/HelloSwing.java
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/679
> Replace `html5test.co` with `html5test.teamdev.com`

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
This PR updates JxBrowser version to 7.38.1 and JxBrowser Gradle plugin version to 1.0.2.
> Bump JxBrowser version to 7.38.1

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 7.39.0
* Update Gradle/Console/build.gradle.kts
* Update Gradle/JavaFX-11/build.gradle.kts
* Update Gradle/JavaFX/build.gradle.kts
* Update Gradle/SWT/build.gradle.kts
* Update Gradle/SWT/buildSrc/build.gradle.kts
* Update Gradle/Swing/build.gradle.kts
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1120
> Update JxBrowser to v7.39.0

- Gradle/Console/build.gradle.kts
- Gradle/Console/settings.gradle.kts
- Gradle/Console/src/main/java/HelloConsole.java
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX-11/settings.gradle.kts
- Gradle/JavaFX-11/src/main/java/HelloFX11.java
- Gradle/JavaFX/build.gradle.kts
- Gradle/JavaFX/settings.gradle.kts
- Gradle/JavaFX/src/main/java/HelloFX.java
- Gradle/SWT/build.gradle.kts
- Gradle/SWT/buildSrc/src/main/kotlin/Swt.kt
- Gradle/SWT/settings.gradle.kts
- Gradle/SWT/src/main/java/HelloSWT.java
- Gradle/Swing/build.gradle.kts
- Gradle/Swing/settings.gradle.kts
- Gradle/Swing/src/main/java/HelloSwing.java
- Maven/Console/pom.xml
- Maven/Console/src/main/java/HelloConsole.java
- Maven/JavaFX/pom.xml
- Maven/JavaFX/src/main/java/HelloFX.java
- Maven/SWT/pom.xml
- Maven/SWT/src/main/java/HelloSWT.java
- Maven/Swing/pom.xml
- Maven/Swing/src/main/java/HelloSwing.java
Bump JxBrowser version to 7.39.2
* Update Gradle/Console/build.gradle.kts
* Update Gradle/JavaFX-11/build.gradle.kts
* Update Gradle/JavaFX/build.gradle.kts
* Update Gradle/SWT/build.gradle.kts
* Update Gradle/SWT/buildSrc/build.gradle.kts
* Update Gradle/Swing/build.gradle.kts
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1286
> Update JxBrowser to v7.39.2

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1594
> Update the JxBrowser version to 7.40.0

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1710
> Update JxBrowser version to 7.41.0

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1799
> Update JxBrowser version to 7.41.1

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Issue: https://github.com/TeamDev-IP/JxBrowser-Docs/issues/1853
> Update JxBrowser version to 7.41.2

- Gradle/Console/src/main/java/HelloConsole.java
- Gradle/JavaFX/src/main/java/HelloFX.java
- Gradle/SWT/src/main/java/HelloSWT.java
- Gradle/Swing/src/main/java/HelloSwing.java
In this changeset, we have utilized Java 17 features in QuickStart guide.
Issue: TeamDev-IP/JxBrowser-Docs/issues/2022
> Use Java 17 features

- Gradle/Compose/build.gradle.kts
- Gradle/Console/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
Bump JxBrowser version to 8.2.0.
> Update JxBrowser version to 8.2.0

- Gradle/Console/build.gradle.kts
- Gradle/JavaFX-11/build.gradle.kts
- Gradle/JavaFX/build.gradle.kts
- Gradle/SWT/build.gradle.kts
- Gradle/Swing/build.gradle.kts
- Maven/Console/pom.xml
- Maven/JavaFX/pom.xml
- Maven/SWT/pom.xml
- Maven/Swing/pom.xml
In this changeset, I have updated JxBrowser version to 7.41.6.
> Update JxBrowser version to 7.41.6
